[
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004394",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제106동 제4층 제403호 [충무공동 191]",
        "owner": "조**",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41202,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 0,
        "sortKey": 0,
        "uniqueKey": "@dataKey1661832626034-0",
        "_attributes": {
            "rowNum": 1,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004396",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제106동 제5층 제501호 [충무공동 191]",
        "owner": "이**",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41203,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 1,
        "sortKey": 1,
        "uniqueKey": "@dataKey1661832626034-1",
        "_attributes": {
            "rowNum": 2,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004408",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제106동 제8층 제801호 [충무공동 191]",
        "owner": "장**외 1명",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41205,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 2,
        "sortKey": 2,
        "uniqueKey": "@dataKey1661832626034-2",
        "_attributes": {
            "rowNum": 3,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004411",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제106동 제8층 제804호 [충무공동 191]",
        "owner": "이**",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41206,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 3,
        "sortKey": 3,
        "uniqueKey": "@dataKey1661832626034-3",
        "_attributes": {
            "rowNum": 4,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004441",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제106동 제16층 제1602호 [충무공동 191]",
        "owner": "구**외 1명",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41207,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 4,
        "sortKey": 4,
        "uniqueKey": "@dataKey1661832626034-4",
        "_attributes": {
            "rowNum": 5,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004443",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제106동 제16층 제1604호 [충무공동 191]",
        "owner": "이**",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41208,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 5,
        "sortKey": 5,
        "uniqueKey": "@dataKey1661832626034-5",
        "_attributes": {
            "rowNum": 6,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004445",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제106동 제17층 제1702호 [충무공동 191]",
        "owner": "김**",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41209,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 6,
        "sortKey": 6,
        "uniqueKey": "@dataKey1661832626034-6",
        "_attributes": {
            "rowNum": 7,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004447",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제106동 제17층 제1704호 [충무공동 191]",
        "owner": "유**외 1명",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41210,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 7,
        "sortKey": 7,
        "uniqueKey": "@dataKey1661832626034-7",
        "_attributes": {
            "rowNum": 8,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004920",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제107동 제4층 제404호 [충무공동 191]",
        "owner": "김**",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41211,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 8,
        "sortKey": 8,
        "uniqueKey": "@dataKey1661832626034-8",
        "_attributes": {
            "rowNum": 9,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    },
    {
        "sStatus": "A",
        "unqNo": "1911-2013-004966",
        "esttCls": "집합건물",
        "esttAddr": "경상남도 진주시 사들로 157 진주혁신도시 센텀리버파크 제107동 제16층 제1602호 [충무공동 191]",
        "owner": "박**",
        "upr": 770,
        "rgstnRecSts": "현행",
        "flag1": 1,
        "flag2": 0,
        "flag3": null,
        "flag4": null,
        "flag5": null,
        "flag6": null,
        "flag7": null,
        "no": 41212,
        "map": "경상남도 진주시 사들로 157",
        "dungbonCls": "12",
        "y202tradeSeqFlag": "Y",
        "y202cmortFlag": "Y",
        "sinchung": "Y",
        "summary": "Y",
        "rowKey": 9,
        "sortKey": 9,
        "uniqueKey": "@dataKey1661832626034-9",
        "_attributes": {
            "rowNum": 10,
            "checked": true,
            "disabled": false,
            "checkDisabled": false,
            "className": {
                "row": [],
                "column": {}
            }
        },
        "_disabledPriority": {},
        "rowSpanMap": {},
        "_relationListItemMap": {}
    }
]